"""
EXPERIMENT 4 -- systematic error: what the inverse crime hides.

Experiments 2 and 3 used the same model to generate and to fit the data.  That
is an inverse crime, and it makes the fitter look far better than any real
instrument.  The reported sigma_d ~ 0.004 nm is a NOISE FLOOR, not an accuracy.

Here the data are generated by a DIFFERENT, more complete model than the one
used to fit, one perturbation at a time:

  S1  unmodelled interfacial SiO_x layer at the SiO2/Si boundary
  S2  surface roughness, modelled as a Bruggeman effective-medium layer
  S3  film index different from bulk fused silica (thermal oxide densification)
  S4  reference-data choice for the substrate: Green 2008 vs Aspnes 1983
  S5  incidence-angle calibration error (design B only)

Each produces a BIAS in the recovered thickness.  Bias does not average down
with repeated measurements and is invisible to the residual RMS if the
perturbation is small -- which is exactly what makes it dangerous.

The output is an error budget table comparing every systematic against the
random floor.
"""

import json

import numpy as np

from _style import plt, C, save, banner, RESULTS
from omf.core import coh_tmm
from omf.fitter import FilmModel
from omf.materials import build_n_list, n_sio2, n_si, n_si_aspnes, n_constant

INF = np.inf
res = {}
budget = []

D_TRUE = 217.3
STACK = ["air", "SiO2", "Si"]
D_LIST = [INF, D_TRUE, INF]

lamC = np.linspace(400.0, 900.0, 251)
thC = 0.0
d_grid = np.linspace(100.0, 350.0, 1000)

# the fitting model -- deliberately the simple one, in every case below
fit_model = FilmModel(STACK, D_LIST, fit_layer=1, pol="s")

RANDOM_FLOOR = 0.00444          # nm, CRLB at sigma_R = 2e-4 (experiment 3)

banner("EXPERIMENT 4 -- SYSTEMATIC ERRORS (inverse crime broken)")
print(f"  truth d = {D_TRUE} nm; fitting model is always air / SiO2(Malitson) / Si(Green)")
print(f"  random floor for comparison: sigma_d = {RANDOM_FLOOR} nm at sigma_R = 2e-4")


def fit_to(R_data, lam=lamC, th=thC, model=fit_model, grid=d_grid):
    fr = model.fit(lam, th, R_data, grid)
    return fr


# ---------------------------------------------------------------------------
# S1 -- unmodelled interfacial layer
# ---------------------------------------------------------------------------
banner("S1 -- UNMODELLED INTERFACIAL SiO_x LAYER")
print("  Real thermal oxide does not meet crystalline Si abruptly. A sub-nm to")
print("  few-nm transition region of sub-stoichiometric SiO_x sits at the")
print("  interface, with an index between SiO2 (1.46) and Si (3.9). We take")
print("  n_int = 2.5 and vary its thickness, then fit with a two-layer model.")
print()
print(f"  {'t_int (nm)':>11s} {'fitted d (nm)':>15s} {'bias (nm)':>12s} "
      f"{'bias/floor':>12s} {'residual RMS':>14s}")

t_ints = [0.0, 0.5, 1.0, 2.0, 3.0]
s1_bias = []
for t in t_ints:
    n_true = build_n_list(["air", "SiO2", n_constant(2.5), "Si"], lamC)
    R = coh_tmm("s", n_true, [INF, D_TRUE, t, INF], thC, lamC)["R"]
    fr = fit_to(R)
    bias = fr.params[0] - D_TRUE
    s1_bias.append(bias)
    print(f"  {t:11.2f} {fr.params[0]:15.4f} {bias:+12.4f} "
          f"{abs(bias)/RANDOM_FLOOR:12.0f} {fr.rms:14.3e}")
res["S1_t_int_nm"] = t_ints
res["S1_bias_nm"] = s1_bias
budget.append(("S1 interfacial layer, 1 nm", s1_bias[t_ints.index(1.0)]))
print()
print(f"  A 1 nm interfacial layer biases d by {s1_bias[t_ints.index(1.0)]:+.3f} nm --")
print(f"  {abs(s1_bias[t_ints.index(1.0)])/RANDOM_FLOOR:.0f}x the random floor. The residual RMS stays at")
print(f"  {fr.rms:.1e}-ish, so a good chi^2 does NOT certify the answer.")

# ---------------------------------------------------------------------------
# S2 -- surface roughness via Bruggeman EMA
# ---------------------------------------------------------------------------
banner("S2 -- SURFACE ROUGHNESS (Bruggeman effective medium)")


def bruggeman(eps_a, eps_b, f_a):
    """Two-phase Bruggeman EMA.

        f_a (eps_a - eps)/(eps_a + 2 eps) + f_b (eps_b - eps)/(eps_b + 2 eps) = 0

    reduces to  2 eps^2 - b eps - eps_a eps_b = 0  with
        b = (3 f_a - 1) eps_a + (2 - 3 f_a) eps_b.
    The physical root is the one with Im(eps) >= 0 (passive medium).
    """
    b = (3.0 * f_a - 1.0) * eps_a + (2.0 - 3.0 * f_a) * eps_b
    disc = np.sqrt(b**2 + 8.0 * eps_a * eps_b)
    e1 = (b + disc) / 4.0
    e2 = (b - disc) / 4.0
    return np.where(e1.imag >= 0, e1, e2)


def n_rough(lam):
    """50 % SiO2 + 50 % void surface layer -- the standard roughness proxy."""
    eps_f = n_sio2(lam) ** 2
    eps_v = np.ones_like(eps_f)
    return np.sqrt(bruggeman(eps_f, eps_v, 0.5))


print(f"  Roughness is represented by a 50/50 film-void Bruggeman layer on top.")
print(f"  n_eff(550 nm) = {n_rough(np.array([550.0]))[0].real:.4f} "
      f"(between 1 and n_SiO2 = {float(n_sio2(550.0).real):.4f}), as expected.")
print()
print(f"  {'t_rough (nm)':>13s} {'fitted d (nm)':>15s} {'bias (nm)':>12s} {'bias/floor':>12s}")
t_rs = [0.0, 1.0, 2.0, 5.0]
s2_bias = []
for t in t_rs:
    n_true = build_n_list(["air", n_rough, "SiO2", "Si"], lamC)
    R = coh_tmm("s", n_true, [INF, t, D_TRUE, INF], thC, lamC)["R"]
    fr = fit_to(R)
    bias = fr.params[0] - D_TRUE
    s2_bias.append(bias)
    print(f"  {t:13.2f} {fr.params[0]:15.4f} {bias:+12.4f} {abs(bias)/RANDOM_FLOOR:12.0f}")
res["S2_t_rough_nm"] = t_rs
res["S2_bias_nm"] = s2_bias
budget.append(("S2 roughness, 2 nm", s2_bias[t_rs.index(2.0)]))
transfer = s2_bias[t_rs.index(2.0)] / 2.0
print()
print(f"  Transfer coefficient: {transfer:.3f} nm of apparent oxide per nm of")
print(f"  rough layer. The rough layer is 50 % SiO2 by volume, so the fit is")
print(f"  reporting, to good approximation, the VOLUME-EQUIVALENT oxide thickness")
print(f"  d + f * t_rough with f ~ 0.5 -- not the physical top-surface position.")
print(f"  The bias is positive because in this geometry the rough layer sits on")
print(f"  top of the full film and therefore ADDS optical path.")
print(f"  Practical consequence: 'thickness' is not a single well-defined number")
print(f"  for a rough film, and two instruments using different roughness")
print(f"  conventions will disagree by ~f * t_rough even if both are working")
print(f"  perfectly. This is a definition problem, not a measurement error.")
res["S2_transfer_coefficient"] = float(transfer)

# ---------------------------------------------------------------------------
# S3 -- film index offset
# ---------------------------------------------------------------------------
banner("S3 -- FILM INDEX: THERMAL OXIDE vs BULK FUSED SILICA")
print("  Thermally grown SiO2 is denser and stressed relative to bulk fused")
print("  silica; literature puts the visible-range index typically 0.002-0.006")
print("  higher. We generate with n = Malitson + dn and fit assuming Malitson.")
print()
print("  Convention: Delta n = n_true - n_assumed (the model always assumes Malitson).")
print("  Since the fringes fix the optical thickness n*d, an assumed index that is")
print("  too LOW must be compensated by a fitted thickness that is too HIGH:")
print("      n_assumed * d_fit = n_true * d_true   =>   bias = + Delta n * d / n.")
print()
print(f"  {'Delta n':>8s} {'fitted d (nm)':>15s} {'bias (nm)':>12s} "
      f"{'predicted +dn*d/n':>20s}")
dns = [0.000, 0.002, 0.004, 0.006]
s3_bias = []
nf_mid = float(n_sio2(650.0).real)
for dn in dns:
    n_true = build_n_list(["air", lambda L, _dn=dn: n_sio2(L) + _dn, "Si"], lamC)
    R = coh_tmm("s", n_true, D_LIST, thC, lamC)["R"]
    fr = fit_to(R)
    bias = fr.params[0] - D_TRUE
    s3_bias.append(bias)
    print(f"  {dn:8.3f} {fr.params[0]:15.4f} {bias:+12.4f} "
          f"{+dn/nf_mid*D_TRUE:20.4f}")
res["S3_dn"] = dns
res["S3_bias_nm"] = s3_bias
budget.append(("S3 film index +0.004", s3_bias[dns.index(0.004)]))
print()
print("  The measured bias tracks the +Delta n * d / n rule closely, confirming that")
print("  what the fringes actually fix is the optical thickness n*d. This is the")
print("  fundamental reason a reflectometer cannot certify a thickness without an")
print("  independent index -- and why ellipsometry, which measures a phase, is")
print("  the reference method.")

# ---------------------------------------------------------------------------
# S4 -- substrate reference data
# ---------------------------------------------------------------------------
banner("S4 -- SUBSTRATE OPTICAL CONSTANTS: GREEN 2008 vs ASPNES 1983")
lam4 = np.linspace(400.0, 820.0, 211)     # Aspnes table valid to 826 nm
print("  Two independent, widely used determinations of Si optical constants.")
print("  Difference in n at selected wavelengths:")
for L in (405.0, 546.0, 633.0, 800.0):
    g, a = n_si(L), n_si_aspnes(L)
    print(f"    {L:6.1f} nm : Green n={g.real:.4f} k={g.imag:.5f} | "
          f"Aspnes n={a.real:.4f} k={a.imag:.5f} | dn={g.real-a.real:+.4f}")

n_true = build_n_list(["air", "SiO2", "Si_Aspnes"], lam4)
R = coh_tmm("s", n_true, D_LIST, thC, lam4)["R"]
fr = fit_to(R, lam=lam4)
bias_S4 = fr.params[0] - D_TRUE
print()
print(f"  data generated with Aspnes, fitted with Green:")
print(f"    fitted d = {fr.params[0]:.4f} nm, bias = {bias_S4:+.4f} nm "
      f"({abs(bias_S4)/RANDOM_FLOOR:.0f}x floor), residual RMS = {fr.rms:.3e}")
res["S4_bias_nm"] = float(bias_S4)
budget.append(("S4 Si reference data", bias_S4))
print()
print("  This is irreducible without an independent measurement: both data sets")
print("  are peer-reviewed and neither is 'wrong'. It must be carried as a")
print("  systematic uncertainty, not eliminated.")

# ---------------------------------------------------------------------------
# S5 -- angle calibration error
# ---------------------------------------------------------------------------
banner("S5 -- INCIDENCE-ANGLE CALIBRATION ERROR (design B)")
th_nom = np.deg2rad(np.linspace(0.0, 70.0, 141))
lamB = np.full(th_nom.shape, 405.0)
print("  Experiment 3 found the angle scan to be intrinsically more precise.")
print("  Here is the price: the angle must be known. Data are generated at")
print("  th_true = th_nominal + delta, and fitted assuming th_nominal.")
print()
print(f"  {'delta (deg)':>12s} {'fitted d (nm)':>15s} {'bias (nm)':>12s} {'bias/floor':>12s}")
deltas = [0.0, 0.05, 0.1, 0.2, 0.5]
s5_bias = []
n_B = build_n_list(STACK, lamB)
for dd in deltas:
    R = coh_tmm("s", n_B, D_LIST, th_nom + np.deg2rad(dd), lamB)["R"]
    fr = fit_to(R, lam=lamB, th=th_nom)
    bias = fr.params[0] - D_TRUE
    s5_bias.append(bias)
    print(f"  {dd:12.2f} {fr.params[0]:15.4f} {bias:+12.4f} "
          f"{abs(bias)/0.00252:12.0f}")
res["S5_delta_deg"] = deltas
res["S5_bias_nm"] = s5_bias
budget.append(("S5 angle error 0.1 deg", s5_bias[deltas.index(0.1)]))

# ---------------------------------------------------------------------------
# error budget
# ---------------------------------------------------------------------------
banner("ERROR BUDGET -- d = 217.3 nm SiO2 on Si, spectroscopic reflectometry")
print(f"  {'source':<34s} {'contribution (nm)':>19s} {'x random floor':>16s}")
print("  " + "-" * 71)
print(f"  {'RANDOM: photometric noise 2e-4':<34s} {RANDOM_FLOOR:19.4f} {1.0:16.1f}")
print("  " + "-" * 71)
tot2 = 0.0
for name, b in budget:
    tot2 += b**2
    print(f"  {name:<34s} {b:+19.4f} {abs(b)/RANDOM_FLOOR:16.0f}")
print("  " + "-" * 71)
rss = np.sqrt(tot2)
print(f"  {'SYSTEMATIC, RSS combined':<34s} {rss:19.4f} {rss/RANDOM_FLOOR:16.0f}")
print(f"  {'TOTAL (random + systematic)':<34s} "
      f"{np.sqrt(rss**2 + RANDOM_FLOOR**2):19.4f}")
print()
print("  CONCLUSION")
print("  ----------")
print(f"  The defensible statement about this pipeline is:")
print(f"      algorithmic noise floor  : ~{RANDOM_FLOOR*1000:.0f} pm  (inverse crime, best case)")
print(f"      realistic accuracy       : ~{rss:.1f} nm  (dominated by model form)")
print(f"  Quoting the first number as an accuracy would overstate the result by")
print(f"  a factor of ~{rss/RANDOM_FLOOR:.0f}. Reducing it requires better SAMPLE knowledge --")
print(f"  independent index, interface and roughness characterisation -- not a")
print(f"  better optimiser.")
res["budget"] = {k: float(v) for k, v in budget}
res["systematic_rss_nm"] = float(rss)
res["random_floor_nm"] = RANDOM_FLOOR

# ---------------------------------------------------------------------------
# figure
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.9))

ax = axes[0]
ax.plot(t_ints, s1_bias, "o-", color=C["blue"], label="interfacial SiO$_x$ (n=2.5)")
ax.plot(t_rs, s2_bias, "s-", color=C["orange"], label="surface roughness (EMA)")
ax.axhline(0, color=C["black"], lw=0.7)
ax.fill_between([0, 5], -RANDOM_FLOOR, RANDOM_FLOOR, color=C["green"],
                alpha=0.3, label="random floor")
ax.set_xlabel("unmodelled layer thickness (nm)")
ax.set_ylabel("thickness bias (nm)")
ax.set_title("(a) unmodelled layers")
ax.legend()

ax = axes[1]
ax.plot(dns, s3_bias, "o-", color=C["purple"], label="fitted bias")
ax.plot(dns, [+x / nf_mid * D_TRUE for x in dns], "--", color=C["grey"],
        label="$+\\Delta n\\,d/n$")
ax.axhline(0, color=C["black"], lw=0.7)
ax.set_xlabel("film index offset $\\Delta n$")
ax.set_ylabel("thickness bias (nm)")
ax.set_title("(b) optical-thickness degeneracy")
ax.legend()

ax = axes[2]
labels = [b[0].split(" ", 1)[0] for b in budget]
vals = [abs(b[1]) for b in budget]
ax.bar(labels, vals, color=C["red"], alpha=0.8)
ax.axhline(RANDOM_FLOOR, color=C["green"], lw=1.4, label="random floor")
ax.set_yscale("log")
ax.set_ylabel("|bias| (nm)")
ax.set_title("(c) error budget")
ax.legend()
ax.grid(axis="x", visible=False)

save(fig, "exp04_systematics.png")

with open(f"{RESULTS}/exp04_results.json", "w") as f:
    json.dump(res, f, indent=2)
print(f"\n    data -> results/exp04_results.json")
